export const sidebarSections = [
  {
    title: 'Core Operations',
    items: [
      { id: 'employee-management', label: 'Employee Management' },
      { id: 'attendance-time', label: 'Attendance & Time' },
      { id: 'fingerprint', label: 'Fingerprint' },
      { id: 'leave-management', label: 'Leave Management' },
      { id: 'payroll-management', label: 'Payroll Management' },
      { id: 'documents-records', label: 'Documents & Records' },
      { id: 'reports-analytics', label: 'Reports & Analytics' },
    ],
  },
  {
    title: 'Platform Control',
    items: [
      { id: 'auth-roles', label: 'Authentication & Roles' },
      { id: 'recruitment', label: 'Recruitment' },
      { id: 'performance', label: 'Performance Evaluation' },
      { id: 'training', label: 'Training Management' },
    ],
  },
  {
    title: 'System',
    items: [{ id: 'settings', label: 'Settings' }],
  },
];

export const moduleUiData = {
  'employee-management': {
    title: 'Employee Management',
    entityLabel: 'Employee',
    filterLabel: 'Department',
    filterField: 'department',
    formFields: [
      { key: 'fullName', label: 'Full Name', required: true },
      { key: 'dob', label: 'Date of Birth', type: 'date', required: true },
      {
        key: 'idCardType',
        label: 'ID Card Type',
        type: 'select',
        required: true,
        options: ['National ID', 'Passport', 'Driver License', 'Voter Card', 'Other'],
      },
      { key: 'idCardNumber', label: 'ID Number', required: true },
      { key: 'phonePrimary', label: 'Phone 1', type: 'tel', required: true },
      { key: 'phoneSecondary', label: 'Phone 2', type: 'tel' },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'password', label: 'Portal Password', type: 'password', required: true },
      { key: 'pensionId', label: 'Pension Number', required: true },
      { key: 'taxId', label: 'Tax ID Number', required: true },
      { key: 'department', label: 'Department', type: 'select', required: true },
      { key: 'position', label: 'Position', required: true },
      { key: 'lineManager', label: 'Line Manager', required: true },
      { key: 'leaveBalanceDays', label: 'Leave Balance (Days)', type: 'number', required: true },
      {
        key: 'contractType',
        label: 'Contract Type',
        type: 'select',
        required: true,
        options: ['Permanent', 'Temporal', 'Piece Work', 'Intern', 'Attachment', 'Other'],
      },
      {
        key: 'contractTypeOther',
        label: 'Specify Contract Type',
        showWhen: { field: 'contractType', value: 'Other' },
      },
      { key: 'contractStartDate', label: 'Contract Start Date', type: 'date', required: true },
      { key: 'contractEndDate', label: 'Contract End Date', type: 'date' },
      { key: 'address', label: 'Address', type: 'textarea', required: true },
      { key: 'passportPhoto', label: 'Passport Photo', type: 'file', required: true },
      { key: 'idFront', label: 'ID Front', type: 'file', required: true },
      { key: 'idBack', label: 'ID Back', type: 'file', required: true },
      { key: 'otherDocuments', label: 'Other Documents', type: 'file', multiple: true },
      { key: 'otherDocumentsNote', label: 'Other Documents Note', type: 'textarea' },
      { key: 'emergencyContact1Name', label: 'Emergency Contact 1 Name', required: true },
      { key: 'emergencyContact1Phone', label: 'Emergency Contact 1 Phone', type: 'tel', required: true },
      { key: 'emergencyContact2Name', label: 'Emergency Contact 2 Name', required: true },
      { key: 'emergencyContact2Phone', label: 'Emergency Contact 2 Phone', type: 'tel', required: true },
      { key: 'referee1', label: 'Referee 1', required: true },
      { key: 'referee2', label: 'Referee 2', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['Active', 'Inactive'],
      },
      {
        key: 'employmentState',
        label: 'Employment Stage',
        type: 'select',
        required: true,
        options: ['Probation', 'Confirmed', 'Suspended', 'On Leave', 'Fired', 'Expired'],
      },
    ],
    columns: [
      { key: 'id', label: 'Employee ID' },
      { key: 'fullName', label: 'Full Name' },
      { key: 'department', label: 'Department' },
      { key: 'position', label: 'Position' },
      { key: 'contractType', label: 'Contract Type' },
      { key: 'status', label: 'Status' },
      { key: 'employmentState', label: 'Employment Stage' },
      { key: 'email', label: 'Email' },
    ],
    rows: [
      {
        id: 'HR00000001',
        fullName: 'Amina Yusuf',
        dob: '1992-02-14',
        idCardType: 'National ID',
        idCardNumber: 'GHA-9012443',
        phonePrimary: '+233241111111',
        phoneSecondary: '+233201111111',
        email: 'amina@pthr.local',
        password: 'Amina@2026',
        pensionId: 'SSNIT-99321107',
        taxId: 'TIN-C004512993',
        department: 'Human Resources',
        position: 'HR Manager',
        lineManager: 'Chief People Officer',
        leaveBalanceDays: '22',
        contractType: 'Permanent',
        contractTypeOther: '',
        contractStartDate: '2021-01-10',
        contractEndDate: '',
        address: 'Accra Central, Ghana',
        passportPhoto: 'amina_passport.jpg',
        idFront: 'amina_id_front.jpg',
        idBack: 'amina_id_back.jpg',
        otherDocuments: 'BSc_HRM.pdf, Recommendation_Amina.pdf',
        emergencyContact1Name: 'Yusuf Ahmed',
        emergencyContact1Phone: '+233241901901',
        emergencyContact2Name: 'Laila Okafor',
        emergencyContact2Phone: '+233244782400',
        referee1: 'Dr. Issah Mensah',
        referee2: 'Mrs. Comfort Addo',
        status: 'Active',
        employmentState: 'Confirmed',
      },
      {
        id: 'EN00000002',
        fullName: 'David Kimani',
        dob: '1994-09-19',
        idCardType: 'Passport',
        idCardNumber: 'KEP778921',
        phonePrimary: '+254712300400',
        phoneSecondary: '',
        email: 'david@pthr.local',
        password: 'David@2026',
        pensionId: 'NSSF-KE-77390112',
        taxId: 'KRA-P051228219N',
        department: 'Engineering',
        position: 'Frontend Engineer',
        lineManager: 'Engineering Lead',
        leaveBalanceDays: '16',
        contractType: 'Permanent',
        contractTypeOther: '',
        contractStartDate: '2022-05-06',
        contractEndDate: '',
        address: 'Westlands, Nairobi',
        passportPhoto: 'david_passport.jpg',
        idFront: 'david_passport_front.jpg',
        idBack: 'david_passport_back.jpg',
        otherDocuments: 'BSc_ComputerScience.pdf',
        emergencyContact1Name: 'Mercy Kimani',
        emergencyContact1Phone: '+254703120120',
        emergencyContact2Name: 'Pauline Mwangi',
        emergencyContact2Phone: '+254700001177',
        referee1: 'Eng. Kelvin Otieno',
        referee2: 'Sarah Naliaka',
        status: 'Active',
        employmentState: 'Probation',
      },
      {
        id: 'FN00000007',
        fullName: 'Fatima Bello',
        dob: '1990-06-03',
        idCardType: 'National ID',
        idCardNumber: 'NGA-7122088',
        phonePrimary: '+2348039001100',
        phoneSecondary: '+2348093300055',
        email: 'fatima@pthr.local',
        password: 'Fatima@2026',
        pensionId: 'PEN-NG-62339012',
        taxId: 'TIN-01227738-11',
        department: 'Finance',
        position: 'Payroll Officer',
        lineManager: 'Finance Director',
        leaveBalanceDays: '10',
        contractType: 'Temporal',
        contractTypeOther: '',
        contractStartDate: '2025-01-01',
        contractEndDate: '2026-12-31',
        address: 'Ikeja, Lagos',
        passportPhoto: 'fatima_passport.jpg',
        idFront: 'fatima_nin_front.jpg',
        idBack: 'fatima_nin_back.jpg',
        otherDocuments: 'MBA_Transcript.pdf, Testimonial_Fatima.pdf',
        emergencyContact1Name: 'Yusuf Bello',
        emergencyContact1Phone: '+2348036000001',
        emergencyContact2Name: 'Maryam Abubakar',
        emergencyContact2Phone: '+2348058803211',
        referee1: 'Chinedu Obasi',
        referee2: 'Aisha Ibrahim',
        status: 'Inactive',
        employmentState: 'On Leave',
      },
      {
        id: 'OP00000011',
        fullName: 'Liam Osei',
        dob: '1988-11-23',
        idCardType: 'Driver License',
        idCardNumber: 'GH-DL-448188',
        phonePrimary: '+233249992222',
        phoneSecondary: '+233278881010',
        email: 'liam@pthr.local',
        password: 'Liam@2026',
        pensionId: 'SSNIT-22041198',
        taxId: 'TIN-GH-90221211',
        department: 'Operations',
        position: 'Operations Analyst',
        lineManager: 'Operations Manager',
        leaveBalanceDays: '14',
        contractType: 'Piece Work',
        contractTypeOther: '',
        contractStartDate: '2025-02-01',
        contractEndDate: '2026-08-31',
        address: 'Tema Community 25',
        passportPhoto: 'liam_passport.jpg',
        idFront: 'liam_dl_front.jpg',
        idBack: 'liam_dl_back.jpg',
        otherDocuments: 'Operations_Certificate.pdf',
        emergencyContact1Name: 'Kofi Osei',
        emergencyContact1Phone: '+233247771234',
        emergencyContact2Name: 'Elsie Ofori',
        emergencyContact2Phone: '+233541000234',
        referee1: 'Nana Odoom',
        referee2: 'Bernice Awuah',
        status: 'Active',
        employmentState: 'Confirmed',
      },
    ],
  },
  'attendance-time': {
    title: 'Attendance & Time Tracking',
    entityLabel: 'Attendance Record',
    filterLabel: 'Shift',
    filterField: 'shift',
    formFields: [
      { key: 'employee', label: 'Employee', required: true },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'shift', label: 'Shift', type: 'select', options: ['Morning', 'Evening', 'Night', 'Remote'] },
      { key: 'checkIn', label: 'Check In', type: 'time' },
      { key: 'checkOut', label: 'Check Out', type: 'time' },
      { key: 'workedHours', label: 'Worked Hours' },
      { key: 'lateMinutes', label: 'Late (Minutes)', type: 'number' },
      { key: 'deductionRatePerMinute', label: 'Deduction Rate / Min' },
      { key: 'deductionAmount', label: 'Deduction Amount' },
      { key: 'source', label: 'Source' },
      { key: 'status', label: 'Status', type: 'select', options: ['On Time', 'Late', 'Absent', 'Incomplete'] },
    ],
    columns: [
      { key: 'id', label: 'Record ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'date', label: 'Date' },
      { key: 'shift', label: 'Shift' },
      { key: 'checkIn', label: 'Check In' },
      { key: 'checkOut', label: 'Check Out' },
      { key: 'lateMinutes', label: 'Late (Min)' },
      { key: 'deductionAmount', label: 'Late Deduction' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      {
        id: 'ATT-221',
        employee: 'Amina Yusuf',
        employeeId: 'HR00000001',
        date: '2026-03-16',
        shift: 'Morning',
        checkIn: '08:05',
        checkOut: '17:01',
        workedHours: '8h 56m',
        lateMinutes: '0',
        deductionRatePerMinute: '0.128',
        deductionAmount: '0.00',
        source: 'Manual Clock',
        status: 'On Time',
      },
      {
        id: 'ATT-222',
        employee: 'David Kimani',
        employeeId: 'EN00000002',
        date: '2026-03-16',
        shift: 'Morning',
        checkIn: '08:22',
        checkOut: '17:09',
        workedHours: '8h 47m',
        lateMinutes: '7',
        deductionRatePerMinute: '0.128',
        deductionAmount: '0.90',
        source: 'Manual Clock',
        status: 'Late',
      },
      {
        id: 'ATT-223',
        employee: 'Fatima Bello',
        employeeId: 'FN00000003',
        date: '2026-03-16',
        shift: 'Remote',
        checkIn: '08:01',
        checkOut: '16:58',
        workedHours: '8h 57m',
        lateMinutes: '0',
        deductionRatePerMinute: '0.128',
        deductionAmount: '0.00',
        source: 'Manual Clock',
        status: 'On Time',
      },
      {
        id: 'ATT-224',
        employee: 'Liam Osei',
        employeeId: 'OP00000004',
        date: '2026-03-16',
        shift: 'Evening',
        checkIn: '14:03',
        checkOut: '',
        workedHours: '',
        lateMinutes: '0',
        deductionRatePerMinute: '0.128',
        deductionAmount: '0.00',
        source: 'Manual Clock',
        status: 'On Time',
      },
    ],
  },
  fingerprint: {
    title: 'Fingerprint Enrollment',
    entityLabel: 'Fingerprint Profile',
    filterLabel: 'Sync Status',
    filterField: 'syncStatus',
    formFields: [
      { key: 'employee', label: 'Employee', required: true },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'deviceUserId', label: 'Device User ID', required: true },
      { key: 'templateQuality', label: 'Template Quality' },
      { key: 'enrolledOn', label: 'Enrolled On' },
      { key: 'syncStatus', label: 'Sync Status', type: 'select', options: ['Synced', 'Queued', 'Simulated', 'Failed'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Enrolled', 'Pending', 'Disabled'] },
    ],
    columns: [
      { key: 'id', label: 'Enrollment ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'deviceUserId', label: 'Device User ID' },
      { key: 'templateQuality', label: 'Template Quality' },
      { key: 'syncStatus', label: 'Sync Status' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      {
        id: 'FPT-101',
        employee: 'Amina Yusuf',
        employeeId: 'HR00000001',
        deviceUserId: 'BIO-1001',
        templateQuality: '92%',
        enrolledOn: '2026-03-10 09:12',
        syncStatus: 'Synced',
        status: 'Enrolled',
      },
      {
        id: 'FPT-102',
        employee: 'David Kimani',
        employeeId: 'EN00000002',
        deviceUserId: 'BIO-1002',
        templateQuality: '89%',
        enrolledOn: '2026-03-10 09:26',
        syncStatus: 'Queued',
        status: 'Enrolled',
      },
    ],
  },
  'leave-management': {
    title: 'Leave Management',
    entityLabel: 'Leave Request',
    filterLabel: 'Type',
    filterField: 'type',
    formFields: [
      { key: 'employee', label: 'Employee' },
      { key: 'type', label: 'Type' },
      { key: 'startDate', label: 'Start Date' },
      { key: 'endDate', label: 'End Date' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Request ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'type', label: 'Type' },
      { key: 'startDate', label: 'Start Date' },
      { key: 'endDate', label: 'End Date' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'LEV-310', employee: 'Fatima Bello', type: 'Annual', startDate: '2026-03-18', endDate: '2026-03-22', status: 'Approved' },
      { id: 'LEV-311', employee: 'Liam Osei', type: 'Sick', startDate: '2026-03-20', endDate: '2026-03-21', status: 'Pending' },
      { id: 'LEV-312', employee: 'Amina Yusuf', type: 'Maternity', startDate: '2026-04-01', endDate: '2026-06-30', status: 'Planned' },
    ],
  },
  'payroll-management': {
    title: 'Payroll Management',
    entityLabel: 'Payroll Record',
    filterLabel: 'Month',
    filterField: 'month',
    formFields: [
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'month', label: 'Month' },
      { key: 'basicPay', label: 'Basic Pay' },
      { key: 'workingDays', label: 'Working Days' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Payroll ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'month', label: 'Month' },
      { key: 'basicPay', label: 'Basic Pay' },
      { key: 'lateMinutes', label: 'Late (Min)' },
      { key: 'deductionRatePerMinute', label: 'Rate / Min' },
      { key: 'lateDeduction', label: 'Late Deduction' },
      { key: 'noClockInPenalty', label: 'No In Penalty' },
      { key: 'noClockOutPenalty', label: 'No Out Penalty' },
      { key: 'absentPenalty', label: 'Absent Penalty' },
      { key: 'totalAttendancePenalty', label: 'Total Attendance Penalty' },
      { key: 'payableAfterLate', label: 'Net Payable' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      {
        id: 'PAY-900',
        employee: 'Amina Yusuf',
        employeeId: 'HR00000001',
        month: 'March 2026',
        basicPay: '1800',
        workingDays: '26',
        status: 'Processing',
      },
      {
        id: 'PAY-901',
        employee: 'David Kimani',
        employeeId: 'EN00000002',
        month: 'March 2026',
        basicPay: '1800',
        workingDays: '26',
        status: 'Processing',
      },
      {
        id: 'PAY-902',
        employee: 'Fatima Bello',
        employeeId: 'FN00000003',
        month: 'March 2026',
        basicPay: '1800',
        workingDays: '26',
        status: 'Processing',
      },
    ],
  },
  'documents-records': {
    title: 'Documents & Records',
    entityLabel: 'Document',
    filterLabel: 'Category',
    filterField: 'category',
    formFields: [
      { key: 'employee', label: 'Employee' },
      { key: 'category', label: 'Category' },
      { key: 'fileName', label: 'File Name' },
      { key: 'uploadedOn', label: 'Uploaded On' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Doc ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'category', label: 'Category' },
      { key: 'fileName', label: 'File Name' },
      { key: 'uploadedOn', label: 'Uploaded On' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'DOC-701', employee: 'Amina Yusuf', category: 'Contract', fileName: 'Amina_Contract.pdf', uploadedOn: '2026-02-12', status: 'Verified' },
      { id: 'DOC-702', employee: 'David Kimani', category: 'ID', fileName: 'David_NationalID.pdf', uploadedOn: '2026-02-20', status: 'Pending Review' },
      { id: 'DOC-703', employee: 'Fatima Bello', category: 'Tax', fileName: 'Fatima_TaxForm.pdf', uploadedOn: '2026-03-01', status: 'Verified' },
    ],
  },
  'reports-analytics': {
    title: 'Reports & Analytics',
    entityLabel: 'Report',
    filterLabel: 'Category',
    filterField: 'category',
    formFields: [
      { key: 'name', label: 'Report Name' },
      { key: 'category', label: 'Category' },
      { key: 'owner', label: 'Owner' },
      { key: 'schedule', label: 'Schedule' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Report ID' },
      { key: 'name', label: 'Report Name' },
      { key: 'category', label: 'Category' },
      { key: 'owner', label: 'Owner' },
      { key: 'schedule', label: 'Schedule' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'REP-510', name: 'Headcount Trend', category: 'Workforce', owner: 'HR Strategy', schedule: 'Weekly', status: 'Active' },
      { id: 'REP-511', name: 'Payroll Variance', category: 'Finance', owner: 'Payroll Team', schedule: 'Monthly', status: 'Active' },
      { id: 'REP-512', name: 'Attendance Heatmap', category: 'Attendance', owner: 'Operations', schedule: 'Daily', status: 'Draft' },
    ],
  },
  'auth-roles': {
    title: 'Authentication & Roles',
    entityLabel: 'Role Rule',
    filterLabel: 'Role',
    filterField: 'role',
    formFields: [
      { key: 'role', label: 'Role' },
      { key: 'resource', label: 'Resource' },
      { key: 'permission', label: 'Permission' },
      { key: 'updatedBy', label: 'Updated By' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Rule ID' },
      { key: 'role', label: 'Role' },
      { key: 'resource', label: 'Resource' },
      { key: 'permission', label: 'Permission' },
      { key: 'updatedBy', label: 'Updated By' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'ACL-01', role: 'HR Manager', resource: 'Employee Profile', permission: 'Read/Write', updatedBy: 'System Admin', status: 'Active' },
      { id: 'ACL-02', role: 'Team Lead', resource: 'Attendance', permission: 'Read/Approve', updatedBy: 'System Admin', status: 'Active' },
      { id: 'ACL-03', role: 'Employee', resource: 'Payroll Slip', permission: 'Read', updatedBy: 'System Admin', status: 'Active' },
    ],
  },
  recruitment: {
    title: 'Recruitment',
    entityLabel: 'Candidate',
    filterLabel: 'Stage',
    filterField: 'stage',
    formFields: [
      { key: 'name', label: 'Candidate Name' },
      { key: 'position', label: 'Position' },
      { key: 'stage', label: 'Stage' },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Candidate ID' },
      { key: 'name', label: 'Name' },
      { key: 'position', label: 'Position' },
      { key: 'stage', label: 'Stage' },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'CAN-100', name: 'Rita Mensah', position: 'Backend Engineer', stage: 'Interview', owner: 'Amina Yusuf', status: 'Active' },
      { id: 'CAN-101', name: 'Joseph Lin', position: 'Product Designer', stage: 'Offer', owner: 'David Kimani', status: 'Pending' },
      { id: 'CAN-102', name: 'Susan Ibe', position: 'HR Associate', stage: 'Screening', owner: 'Amina Yusuf', status: 'Active' },
    ],
  },
  performance: {
    title: 'Performance Evaluation',
    entityLabel: 'Review Cycle',
    filterLabel: 'Cycle',
    filterField: 'cycle',
    formFields: [
      { key: 'cycle', label: 'Cycle' },
      { key: 'department', label: 'Department' },
      { key: 'owner', label: 'Owner' },
      { key: 'completion', label: 'Completion' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Review ID' },
      { key: 'cycle', label: 'Cycle' },
      { key: 'department', label: 'Department' },
      { key: 'owner', label: 'Owner' },
      { key: 'completion', label: 'Completion' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'PER-200', cycle: 'Q1 2026', department: 'Engineering', owner: 'Head of Engineering', completion: '72%', status: 'In Progress' },
      { id: 'PER-201', cycle: 'Q1 2026', department: 'Finance', owner: 'Finance Lead', completion: '84%', status: 'In Progress' },
      { id: 'PER-202', cycle: 'Q4 2025', department: 'Operations', owner: 'COO', completion: '100%', status: 'Completed' },
    ],
  },
  training: {
    title: 'Training Management',
    entityLabel: 'Training Program',
    filterLabel: 'Track',
    filterField: 'track',
    formFields: [
      { key: 'program', label: 'Program' },
      { key: 'track', label: 'Track' },
      { key: 'facilitator', label: 'Facilitator' },
      { key: 'participants', label: 'Participants' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Training ID' },
      { key: 'program', label: 'Program' },
      { key: 'track', label: 'Track' },
      { key: 'facilitator', label: 'Facilitator' },
      { key: 'participants', label: 'Participants' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'TRN-901', program: 'Leadership Essentials', track: 'Management', facilitator: 'Coach Bright', participants: '24', status: 'Scheduled' },
      { id: 'TRN-902', program: 'Compliance Basics', track: 'Policy', facilitator: 'Legal Team', participants: '84', status: 'Ongoing' },
      { id: 'TRN-903', program: 'Frontend Upskilling', track: 'Technical', facilitator: 'Engineering Guild', participants: '31', status: 'Planned' },
    ],
  },
};
