export const sidebarSections = [
  {
    title: 'Core Operations',
    items: [
      { id: 'employee-management', label: 'Employee Management' },
      { id: 'attendance-time', label: 'Attendance & Time' },
      { id: 'loan-records', label: 'Loan Records' },
      { id: 'fingerprint', label: 'Fingerprint' },
      { id: 'leave-management', label: 'Leave Management' },
      { id: 'payroll-management', label: 'Payroll Management' },
      { id: 'documents-records', label: 'Documents & Records' },
      { id: 'reports-analytics', label: 'Reports & Analytics' },
    ],
  },
  {
    title: 'Platform Control',
    items: [
      { id: 'auth-roles', label: 'Authentication & Roles' },
      { id: 'recruitment', label: 'Recruitment' },
      { id: 'performance', label: 'Performance Evaluation' },
      { id: 'training', label: 'Training Management' },
      { id: 'monitoring-tracking', label: 'Monitoring & Tracking' },
    ],
  },
  {
    title: 'System',
    items: [
      { id: 'user-management', label: 'User Management' },
      { id: 'settings', label: 'Settings' },
    ],
  },
];

export const moduleUiData = {
  'employee-management': {
    title: 'Employee Management',
    entityLabel: 'Employee',
    filterLabel: 'Department',
    filterField: 'department',
    formFields: [
      { key: 'fullName', label: 'Full Name', required: true },
      { key: 'dob', label: 'Date of Birth', type: 'date', required: true },
      {
        key: 'idCardType',
        label: 'ID Card Type',
        type: 'select',
        required: true,
        options: ['National ID', 'Passport', 'Driver License', 'Voter Card', 'Other'],
      },
      { key: 'idCardNumber', label: 'ID Number', required: true },
      { key: 'nhimaNumber', label: 'NHIMA Number' },
      { key: 'phonePrimary', label: 'Phone 1', type: 'tel', required: true },
      { key: 'phoneSecondary', label: 'Phone 2', type: 'tel' },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'password', label: 'Portal Password', type: 'password', required: true },
      { key: 'pensionId', label: 'Pension Number', required: true },
      { key: 'taxId', label: 'Tax ID Number', required: true },
      { key: 'mobileMoneyNumber', label: 'Mobile Money Number' },
      { key: 'mobileMoneyNetwork', label: 'MNO' },
      { key: 'mobileMoneyName', label: 'Mobile Money Name' },
      { key: 'bankName', label: 'Bank Name' },
      { key: 'bankAccountNumber', label: 'Bank Account Number' },
      { key: 'bankAccountName', label: 'Bank Account Name' },
      { key: 'accessAccount', label: 'Access Account' },
      { key: 'basicPay', label: 'Basic Pay', type: 'number' },
      { key: 'monthlyBonuses', label: 'Monthly Bonuses', type: 'number' },
      { key: 'transportAllowance', label: 'Transport Allowance', type: 'number' },
      { key: 'housingAllowance', label: 'Housing Allowance', type: 'number' },
      { key: 'foodAllowance', label: 'Food Allowance', type: 'number' },
      { key: 'bankBranchName', label: 'Bank Branch Name' },
      { key: 'bankBranchCode', label: 'Bank Branch Code' },
      { key: 'department', label: 'Department', type: 'select', required: true },
      { key: 'position', label: 'Position', required: true },
      { key: 'lineManager', label: 'Line Manager', required: true },
      { key: 'leaveBalanceDays', label: 'Leave Balance (Days)', type: 'number', required: true },
      {
        key: 'contractType',
        label: 'Contract Type',
        type: 'select',
        required: true,
        options: ['Permanent', 'Temporal', 'Piece Work', 'Intern', 'Attachment', 'Other'],
      },
      {
        key: 'contractTypeOther',
        label: 'Specify Contract Type',
        showWhen: { field: 'contractType', value: 'Other' },
      },
      { key: 'contractStartDate', label: 'Contract Start Date', type: 'date', required: true },
      { key: 'contractEndDate', label: 'Contract End Date', type: 'date' },
      { key: 'address', label: 'Address', type: 'textarea', required: true },
      { key: 'passportPhoto', label: 'Passport Photo', type: 'file', required: true },
      { key: 'idFront', label: 'ID Front', type: 'file', required: true },
      { key: 'idBack', label: 'ID Back', type: 'file', required: true },
      { key: 'otherDocuments', label: 'Other Documents', type: 'file', multiple: true },
      { key: 'otherDocumentsNote', label: 'Other Documents Note', type: 'textarea' },
      { key: 'emergencyContact1Name', label: 'Emergency Contact 1 Name', required: true },
      { key: 'emergencyContact1Phone', label: 'Emergency Contact 1 Phone', type: 'tel', required: true },
      { key: 'emergencyContact2Name', label: 'Emergency Contact 2 Name', required: true },
      { key: 'emergencyContact2Phone', label: 'Emergency Contact 2 Phone', type: 'tel', required: true },
      { key: 'referee1', label: 'Referee 1', required: true },
      { key: 'referee2', label: 'Referee 2', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['Active', 'Inactive'],
      },
      {
        key: 'employmentState',
        label: 'Employment Stage',
        type: 'select',
        required: true,
        options: ['Probation', 'Confirmed', 'Suspended', 'On Leave', 'Fired', 'Expired'],
      },
    ],
    columns: [
      { key: 'id', label: 'Employee ID' },
      { key: 'fullName', label: 'Full Name' },
      { key: 'department', label: 'Department' },
      { key: 'position', label: 'Position' },
      { key: 'contractType', label: 'Contract Type' },
      { key: 'status', label: 'Status' },
      { key: 'employmentState', label: 'Employment Stage' },
      { key: 'email', label: 'Email' },
    ],
    rows: [],
  },
  'attendance-time': {
    title: 'Attendance & Time Tracking',
    entityLabel: 'Attendance Record',
    filterLabel: 'Shift',
    filterField: 'shift',
    formFields: [
      { key: 'employee', label: 'Employee', required: true },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'shift', label: 'Shift', type: 'select', options: ['Morning', 'Evening', 'Night', 'Remote'] },
      { key: 'checkIn', label: 'Check In', type: 'time' },
      { key: 'checkOut', label: 'Check Out', type: 'time' },
      { key: 'workedHours', label: 'Worked Hours' },
      { key: 'lateMinutes', label: 'Late (Minutes)', type: 'number' },
      { key: 'deductionRatePerMinute', label: 'Deduction Rate / Min' },
      { key: 'deductionAmount', label: 'Deduction Amount' },
      { key: 'source', label: 'Source' },
      { key: 'status', label: 'Status', type: 'select', options: ['On Time', 'Late', 'Absent', 'Incomplete'] },
    ],
    columns: [
      { key: 'id', label: 'Record ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'date', label: 'Date' },
      { key: 'shift', label: 'Shift' },
      { key: 'checkIn', label: 'Check In' },
      { key: 'checkOut', label: 'Check Out' },
      { key: 'lateMinutes', label: 'Late (Min)' },
      { key: 'deductionAmount', label: 'Late Deduction' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      {
        id: 'ATT-221',
        employee: 'Amina Yusuf',
        employeeId: 'HR00000001',
        date: '2026-03-16',
        shift: 'Morning',
        checkIn: '08:05',
        checkOut: '17:01',
        workedHours: '8h 56m',
        lateMinutes: '0',
        deductionRatePerMinute: '0.128',
        deductionAmount: '0.00',
        source: 'Manual Clock',
        status: 'On Time',
      },
      {
        id: 'ATT-222',
        employee: 'David Kimani',
        employeeId: 'EN00000002',
        date: '2026-03-16',
        shift: 'Morning',
        checkIn: '08:22',
        checkOut: '17:09',
        workedHours: '8h 47m',
        lateMinutes: '7',
        deductionRatePerMinute: '0.128',
        deductionAmount: '0.90',
        source: 'Manual Clock',
        status: 'Late',
      },
      {
        id: 'ATT-223',
        employee: 'Fatima Bello',
        employeeId: 'FN00000003',
        date: '2026-03-16',
        shift: 'Remote',
        checkIn: '08:01',
        checkOut: '16:58',
        workedHours: '8h 57m',
        lateMinutes: '0',
        deductionRatePerMinute: '0.128',
        deductionAmount: '0.00',
        source: 'Manual Clock',
        status: 'On Time',
      },
      {
        id: 'ATT-224',
        employee: 'Liam Osei',
        employeeId: 'OP00000004',
        date: '2026-03-16',
        shift: 'Evening',
        checkIn: '14:03',
        checkOut: '',
        workedHours: '',
        lateMinutes: '0',
        deductionRatePerMinute: '0.128',
        deductionAmount: '0.00',
        source: 'Manual Clock',
        status: 'On Time',
      },
    ],
  },
  'monitoring-tracking': {
    title: 'Monitoring & Tracking',
    entityLabel: 'Tracking Record',
    filterLabel: 'Status',
    filterField: 'status',
    formFields: [],
    columns: [
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'fullName', label: 'Employee' },
      { key: 'status', label: 'Status' },
      { key: 'distanceMeters', label: 'Distance (m)' },
      { key: 'lastSeen', label: 'Last Seen' },
    ],
    rows: [],
  },
  'loan-records': {
    title: 'Loan Records',
    entityLabel: 'Loan Record',
    filterLabel: 'Status',
    filterField: 'status',
    formFields: [
      { key: 'employee', label: 'Employee', required: true },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'type', label: 'Loan Type', required: true },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'interestPercent', label: 'Interest % / Month', type: 'number' },
      { key: 'tenorMonths', label: 'Tenor (Months)', type: 'number' },
      { key: 'monthlyInstallment', label: 'Monthly Installment', type: 'number' },
      { key: 'issuedOn', label: 'Issued On', type: 'date', required: true },
      { key: 'balance', label: 'Balance', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Closed'] },
    ],
    columns: [
      { key: 'id', label: 'Loan ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'type', label: 'Loan Type' },
      { key: 'amount', label: 'Amount' },
      { key: 'interestPercent', label: 'Interest % / Month' },
      { key: 'tenorMonths', label: 'Tenor (Months)' },
      { key: 'monthlyInstallment', label: 'Monthly Installment' },
      { key: 'issuedOn', label: 'Issued On' },
      { key: 'balance', label: 'Balance' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      {
        id: 'LON-100',
        employee: 'Amina Yusuf',
        employeeId: 'HR00000001',
        type: 'Salary Advance',
        amount: '2500',
        issuedOn: '2026-01-18',
        balance: '1200',
        status: 'Active',
      },
      {
        id: 'LON-101',
        employee: 'Liam Osei',
        employeeId: 'OP00000011',
        type: 'Medical Loan',
        amount: '4000',
        issuedOn: '2025-12-05',
        balance: '600',
        status: 'Active',
      },
      {
        id: 'LON-102',
        employee: 'Fatima Bello',
        employeeId: 'FN00000007',
        type: 'Emergency Loan',
        amount: '850000',
        issuedOn: '2025-09-12',
        balance: '0',
        status: 'Closed',
      },
    ],
  },
  fingerprint: {
    title: 'Fingerprint Enrollment',
    entityLabel: 'Fingerprint Profile',
    filterLabel: 'Sync Status',
    filterField: 'syncStatus',
    formFields: [
      { key: 'employee', label: 'Employee', required: true },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'deviceUserId', label: 'Device User ID', required: true },
      { key: 'templateQuality', label: 'Template Quality' },
      { key: 'enrolledOn', label: 'Enrolled On' },
      { key: 'syncStatus', label: 'Sync Status', type: 'select', options: ['Synced', 'Queued', 'Simulated', 'Failed'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Enrolled', 'Pending', 'Disabled'] },
    ],
    columns: [
      { key: 'id', label: 'Enrollment ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'deviceUserId', label: 'Device User ID' },
      { key: 'templateQuality', label: 'Template Quality' },
      { key: 'syncStatus', label: 'Sync Status' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      {
        id: 'FPT-101',
        employee: 'Amina Yusuf',
        employeeId: 'HR00000001',
        deviceUserId: 'BIO-1001',
        templateQuality: '92%',
        enrolledOn: '2026-03-10 09:12',
        syncStatus: 'Synced',
        status: 'Enrolled',
      },
      {
        id: 'FPT-102',
        employee: 'David Kimani',
        employeeId: 'EN00000002',
        deviceUserId: 'BIO-1002',
        templateQuality: '89%',
        enrolledOn: '2026-03-10 09:26',
        syncStatus: 'Queued',
        status: 'Enrolled',
      },
    ],
  },
  'leave-management': {
    title: 'Leave Management',
    entityLabel: 'Leave Request',
    filterLabel: 'Type',
    filterField: 'type',
    formFields: [
      { key: 'leaveEmployeeSearch', label: 'Employee Search' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'department', label: 'Department' },
      { key: 'type', label: 'Type' },
      { key: 'startDate', label: 'Start Date' },
      { key: 'endDate', label: 'End Date' },
      { key: 'daysRequested', label: 'Days Requested' },
      { key: 'reason', label: 'Reason', type: 'textarea' },
      { key: 'departmentApproval', label: 'Department Approval', type: 'select', options: ['Pending', 'Approved', 'Rejected'] },
      { key: 'hrApproval', label: 'HR Approval', type: 'select', options: ['Pending', 'Approved', 'Rejected'] },
      { key: 'managerApproval', label: 'Manager Approval', type: 'select', options: ['Pending', 'Approved', 'Rejected'] },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Request ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'department', label: 'Department' },
      { key: 'type', label: 'Type' },
      { key: 'startDate', label: 'Start Date' },
      { key: 'endDate', label: 'End Date' },
      { key: 'daysRequested', label: 'Days' },
      { key: 'departmentApproval', label: 'Department Approval' },
      { key: 'hrApproval', label: 'HR Approval' },
      { key: 'managerApproval', label: 'Manager Approval' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      {
        id: 'LEV-310',
        employee: 'Fatima Bello',
        employeeId: 'FN00000003',
        department: 'Finance',
        type: 'Annual',
        startDate: '2026-03-18',
        endDate: '2026-03-22',
        daysRequested: '5',
        reason: 'Family travel',
        departmentApproval: 'Approved',
        managerApproval: 'Approved',
        hrApproval: 'Approved',
        status: 'Approved',
      },
      {
        id: 'LEV-311',
        employee: 'Liam Osei',
        employeeId: 'IT00000004',
        department: 'Information Technology',
        type: 'Sick',
        startDate: '2026-03-20',
        endDate: '2026-03-21',
        daysRequested: '2',
        reason: 'Medical checkup',
        departmentApproval: 'Pending',
        managerApproval: 'Pending',
        hrApproval: 'Pending',
        status: 'Pending Department',
      },
      {
        id: 'LEV-312',
        employee: 'Amina Yusuf',
        employeeId: 'HR00000001',
        department: 'Human Resources',
        type: 'Maternity',
        startDate: '2026-04-01',
        endDate: '2026-06-30',
        daysRequested: '91',
        reason: 'Maternity leave period',
        departmentApproval: 'Approved',
        hrApproval: 'Pending',
        managerApproval: 'Pending',
        status: 'Pending HR',
      },
    ],
  },
  'payroll-management': {
    title: 'Payroll Management',
    entityLabel: 'Payroll Record',
    filterLabel: 'Month',
    filterField: 'month',
    formFields: [
      { key: 'employee', label: 'Employee', required: true },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'month', label: 'Month', required: true },
      { key: 'taxId', label: 'Tax ID' },
      { key: 'pensionId', label: 'NAPSA Number' },
      { key: 'nhimaNumber', label: 'NHIMA Number' },
      { key: 'accessAccount', label: 'Access Account' },
      { key: 'mobileMoneyNumber', label: 'Momo Number' },
      { key: 'mobileMoneyNetwork', label: 'MNO' },
      { key: 'bankName', label: 'Bank Name' },
      { key: 'bankAccountName', label: 'Bank Account Name' },
      { key: 'bankAccountNumber', label: 'Bank Account Number' },
      { key: 'basicPay', label: 'Basic Pay', type: 'number', required: true },
      { key: 'monthlyBonuses', label: 'Monthly Bonuses', type: 'number' },
      { key: 'transportAllowance', label: 'Transport Allowance', type: 'number' },
      { key: 'housingAllowance', label: 'Housing Allowance', type: 'number' },
      { key: 'foodAllowance', label: 'Food Allowance', type: 'number' },
      { key: 'grossPay', label: 'GROSS', type: 'number' },
      { key: 'napsaDeduction', label: 'NAPSA Deduction', type: 'number' },
      { key: 'nhimaDeduction', label: 'NHIMA Deduction', type: 'number' },
      { key: 'taxDeduction', label: 'Tax Deduction', type: 'number' },
      { key: 'otherDeduction', label: 'Other Deduction', type: 'number' },
      { key: 'totalAttendancePenalty', label: 'Total Attendance Penalty', type: 'number' },
      { key: 'totalDeductions', label: 'Total Deductions', type: 'number' },
      { key: 'netPayable', label: 'Net Payable', type: 'number' },
      { key: 'workingDays', label: 'Working Days', type: 'number' },
      { key: 'lateMinutes', label: 'Late (Min)', type: 'number' },
      { key: 'deductionRatePerMinute', label: 'Rate / Min', type: 'number' },
      { key: 'lateDeduction', label: 'Late Deduction', type: 'number' },
      { key: 'noClockInPenalty', label: 'No In Penalty', type: 'number' },
      { key: 'noClockOutPenalty', label: 'No Out Penalty', type: 'number' },
      { key: 'absentPenalty', label: 'Absent Penalty', type: 'number' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Payroll ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'employeeId', label: 'Employee ID' },
      { key: 'month', label: 'Month' },
      { key: 'taxId', label: 'Tax ID' },
      { key: 'pensionId', label: 'NAPSA Number' },
      { key: 'nhimaNumber', label: 'NHIMA Number' },
      { key: 'accessAccount', label: 'Access Account' },
      { key: 'mobileMoneyNumber', label: 'Momo Number' },
      { key: 'mobileMoneyNetwork', label: 'MNO' },
      { key: 'bankName', label: 'Bank Name' },
      { key: 'bankAccountName', label: 'Bank Account Name' },
      { key: 'bankAccountNumber', label: 'Bank Account Number' },
      { key: 'basicPay', label: 'Basic Pay' },
      { key: 'monthlyBonuses', label: 'Monthly Bonuses' },
      { key: 'transportAllowance', label: 'Transport Allowance' },
      { key: 'housingAllowance', label: 'Housing Allowance' },
      { key: 'foodAllowance', label: 'Food Allowance' },
      { key: 'grossPay', label: 'GROSS' },
      { key: 'napsaDeduction', label: 'NAPSA Deduction' },
      { key: 'nhimaDeduction', label: 'NHIMA Deduction' },
      { key: 'taxDeduction', label: 'Tax Deduction' },
      { key: 'otherDeduction', label: 'Other Deduction' },
      { key: 'totalAttendancePenalty', label: 'Total Attendance Penalty' },
      { key: 'totalDeductions', label: 'Total Deductions' },
      { key: 'netPayable', label: 'Net Payable' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      {
        id: 'PAY-900',
        employee: 'Amina Yusuf',
        employeeId: 'HR00000001',
        month: 'March 2026',
        basicPay: '1800',
        workingDays: '26',
        status: 'Processing',
      },
      {
        id: 'PAY-901',
        employee: 'David Kimani',
        employeeId: 'EN00000002',
        month: 'March 2026',
        basicPay: '1800',
        workingDays: '26',
        status: 'Processing',
      },
      {
        id: 'PAY-902',
        employee: 'Fatima Bello',
        employeeId: 'FN00000003',
        month: 'March 2026',
        basicPay: '1800',
        workingDays: '26',
        status: 'Processing',
      },
    ],
  },
  'documents-records': {
    title: 'Documents & Records',
    entityLabel: 'Document',
    filterLabel: 'Category',
    filterField: 'category',
    formFields: [
      { key: 'employee', label: 'Employee' },
      { key: 'category', label: 'Category' },
      { key: 'fileName', label: 'File Name' },
      { key: 'uploadedOn', label: 'Uploaded On' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Doc ID' },
      { key: 'employee', label: 'Employee' },
      { key: 'category', label: 'Category' },
      { key: 'fileName', label: 'File Name' },
      { key: 'uploadedOn', label: 'Uploaded On' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'DOC-701', employee: 'Amina Yusuf', category: 'Contract', fileName: 'Amina_Contract.pdf', uploadedOn: '2026-02-12', status: 'Verified' },
      { id: 'DOC-702', employee: 'David Kimani', category: 'ID', fileName: 'David_NationalID.pdf', uploadedOn: '2026-02-20', status: 'Pending Review' },
      { id: 'DOC-703', employee: 'Fatima Bello', category: 'Tax', fileName: 'Fatima_TaxForm.pdf', uploadedOn: '2026-03-01', status: 'Verified' },
    ],
  },
  'reports-analytics': {
    title: 'Reports & Analytics',
    entityLabel: 'Report',
    filterLabel: 'Category',
    filterField: 'category',
    formFields: [
      { key: 'name', label: 'Report Name' },
      { key: 'category', label: 'Category' },
      { key: 'owner', label: 'Owner' },
      { key: 'schedule', label: 'Schedule' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Report ID' },
      { key: 'name', label: 'Report Name' },
      { key: 'category', label: 'Category' },
      { key: 'owner', label: 'Owner' },
      { key: 'schedule', label: 'Schedule' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'REP-510', name: 'Headcount Trend', category: 'Workforce', owner: 'HR Strategy', schedule: 'Weekly', status: 'Active' },
      { id: 'REP-511', name: 'Payroll Variance', category: 'Finance', owner: 'Payroll Team', schedule: 'Monthly', status: 'Active' },
      { id: 'REP-512', name: 'Attendance Heatmap', category: 'Attendance', owner: 'Operations', schedule: 'Daily', status: 'Draft' },
    ],
  },
  'auth-roles': {
    title: 'Authentication & Roles',
    entityLabel: 'Role',
    filterLabel: 'Role',
    filterField: 'name',
    formFields: [
      { key: 'name', label: 'Role Name', required: true },
      { key: 'description', label: 'Description' },
      { key: 'allowedModules', label: 'Allowed Modules (comma separated ids)' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Role ID' },
      { key: 'name', label: 'Role Name' },
      { key: 'allowedModules', label: 'Allowed Modules' },
      { key: 'status', label: 'Status' },
    ],
    rows: [],
  },
  recruitment: {
    title: 'Recruitment',
    entityLabel: 'Candidate',
    filterLabel: 'Stage',
    filterField: 'stage',
    formFields: [
      { key: 'name', label: 'Candidate Name' },
      { key: 'position', label: 'Position' },
      { key: 'stage', label: 'Stage' },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Candidate ID' },
      { key: 'name', label: 'Name' },
      { key: 'position', label: 'Position' },
      { key: 'stage', label: 'Stage' },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'CAN-100', name: 'Rita Mensah', position: 'Backend Engineer', stage: 'Interview', owner: 'Amina Yusuf', status: 'Active' },
      { id: 'CAN-101', name: 'Joseph Lin', position: 'Product Designer', stage: 'Offer', owner: 'David Kimani', status: 'Pending' },
      { id: 'CAN-102', name: 'Susan Ibe', position: 'HR Associate', stage: 'Screening', owner: 'Amina Yusuf', status: 'Active' },
    ],
  },
  performance: {
    title: 'Performance Evaluation',
    entityLabel: 'Review Cycle',
    filterLabel: 'Cycle',
    filterField: 'cycle',
    formFields: [
      { key: 'cycle', label: 'Cycle' },
      { key: 'department', label: 'Department' },
      { key: 'owner', label: 'Owner' },
      { key: 'completion', label: 'Completion' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Review ID' },
      { key: 'cycle', label: 'Cycle' },
      { key: 'department', label: 'Department' },
      { key: 'owner', label: 'Owner' },
      { key: 'completion', label: 'Completion' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'PER-200', cycle: 'Q1 2026', department: 'Engineering', owner: 'Head of Engineering', completion: '72%', status: 'In Progress' },
      { id: 'PER-201', cycle: 'Q1 2026', department: 'Finance', owner: 'Finance Lead', completion: '84%', status: 'In Progress' },
      { id: 'PER-202', cycle: 'Q4 2025', department: 'Operations', owner: 'COO', completion: '100%', status: 'Completed' },
    ],
  },
  training: {
    title: 'Training Management',
    entityLabel: 'Training Program',
    filterLabel: 'Track',
    filterField: 'track',
    formFields: [
      { key: 'program', label: 'Program' },
      { key: 'track', label: 'Track' },
      { key: 'facilitator', label: 'Facilitator' },
      { key: 'participants', label: 'Participants' },
      { key: 'status', label: 'Status' },
    ],
    columns: [
      { key: 'id', label: 'Training ID' },
      { key: 'program', label: 'Program' },
      { key: 'track', label: 'Track' },
      { key: 'facilitator', label: 'Facilitator' },
      { key: 'participants', label: 'Participants' },
      { key: 'status', label: 'Status' },
    ],
    rows: [
      { id: 'TRN-901', program: 'Leadership Essentials', track: 'Management', facilitator: 'Coach Bright', participants: '24', status: 'Scheduled' },
      { id: 'TRN-902', program: 'Compliance Basics', track: 'Policy', facilitator: 'Legal Team', participants: '84', status: 'Ongoing' },
      { id: 'TRN-903', program: 'Frontend Upskilling', track: 'Technical', facilitator: 'Engineering Guild', participants: '31', status: 'Planned' },
    ],
  },
  'user-management': {
    title: 'User Management',
    entityLabel: 'User',
    filterLabel: 'Role',
    filterField: 'role',
    formFields: [
      { key: 'username', label: 'Username', required: true },
      { key: 'fullName', label: 'Full Name' },
      { key: 'role', label: 'Role' },
      { key: 'allowedModules', label: 'Allowed Modules' },
      { key: 'isActive', label: 'Active Status' },
    ],
    columns: [
      { key: 'id', label: 'User ID' },
      { key: 'username', label: 'Username' },
      { key: 'fullName', label: 'Full Name' },
      { key: 'role', label: 'Role' },
      { key: 'allowedModules', label: 'Allowed Modules' },
      { key: 'isActive', label: 'Status' },
    ],
    rows: [],
  },
};
